### ISSUE TITLE
[idea] Convert kong into a Go module of testcontainers-go

### ISSUE THREAD

**Issue by mdelapenya** [gAmUssA/testcontainers-go-kong#12]
Hi from testcontainers-go 👋 

Given we are starting to add Go modules for the technologies that are used for testing, I wonder if you'd be interested in adding a Go module in testcontainers-go for Kong 🤔 

In the case you are interested, we have docs on how to create a module here: https://golang.testcontainers.org/modules/, and also we offer our assistance while creating it.

Does it sound good to you?

**Comment by gAmUssA** [comment]
@mdelapenya hey! yes, in coming weeks I'm planning to add more functionality to this module (specifically for plugin developers)

**Comment by gAmUssA** [comment]
FYI @mdelapenya WIP #17

**Comment by gAmUssA** [comment]
implemented #18
